### ISSUE TITLE
Enterprise Connector

### ISSUE THREAD

**Issue by pinterid** [snek-at/ec#1]
**User Stories**
- As user I want to be able to register on SNEK by using my company GitLab account, in order to visualize my contributions.

**Is your feature request related to a problem? Please describe.**
The enterprise connector should be used to enable registration of users from non public instances.

**Describe the solution you'd like**
The blue path describes the basic solution for the enterprise connector.
![image](https://user-images.githubusercontent.com/55298934/88191342-a1ecaa00-cc3b-11ea-8877-1bbe32f799bd.png)

The code should be kept as small as possible to make it easy for others to read through it.

***Engine - EC - OPS - SITP Workflow Overview***

![image](https://user-images.githubusercontent.com/52858351/88515682-601d8400-cfec-11ea-8a12-4420f78387d7.png)

Solutions that can be implemented:
- Verification E-Mail (https://github.com/snek-at/engine):
  + Update registration mutation
- Update Database (https://github.com/snek-at/engine): 
  + RAW field
  + Enterprise Page
- Update API (https://github.com/snek-at/engine):
  + RAW mutation
  + Enterprise Page creation
- Configure GItLab:
  + Add User (SNEKman)
- API Endpoint for OPS

**Requirements**
- [x] Enterprise Connector Concept. #2 
- [x] Local GitLab Server for Enterprise Connector. #3 
- [x] Template Repository for Flask. #4
- [x] Update the coding Guideline for Python. https://github.com/snek-at/tonic/issues/6 

**Milestones**
<table>
   <tbody>
      <tr>
         <th align="left" width=200px><b>Feature Milestones</b></th>
         <th align="left" width=250px>Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Feature Designed</td>
         <td>Thu, 23 Jul 2020 13:47:33 +0200</td>
      </tr>
      <tr>
         <td>Requirements Fulfilled</td>
         <td>Mon, 27 Jul 2020 14:07:38 +0200</td>
      </tr>
      <tr>
         <td>Feature Reviewed</td>
         <td>Mon, 27 Jul 2020 14:11:25 +0200</td>
      </tr>
      <tr>
         <th align="left"><b>Opportunity Milestones</b></th>
         <th align="left">Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Implementation Done</td>
         <td></td>
      </tr>
      <tr>
         <td>Implementation Reviewed</td>
         <td></td>
      </tr>
      <tr>
         <td>Implementation Deployed</td>
         <td></td>
      </tr>
   </tbody>
</table>
